loja/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TODO: Remover
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('listarpedidos/', views.ListarPedidos.as_view(), name='listarpedidos'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
]

pedido/models.py
from django.db import models
from django.contrib.auth.models import User

class Pedido(models.Model):

    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default='C',
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
        )
    )

    def __str__(self):
        return f'Pedido N. {self.pk}'  #pega a primary key (id) do pedido

class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=50)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length=50)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=3000)

    def __str__(self):
        return f'Item do {self.pedido}'

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'

pedido/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.views.generic import ListView, DetailView
from django.http import HttpResponse
from django.contrib import messages
from produto.models import Variacao
from helpers import helpers
from .models import Pedido, ItemPedido


class DispatchLoginRequeriredMixin(View):
    # Método que verifica se o usuário esta logado se ele tentar acessar algum pedido pela url
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')

        return super().dispatch(*args, **kwargs)

    # mostra apenas as informações do usuário logado
    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        # filtra a consulta pelo usuario logado
        qs = qs.filter(usuario=self.request.user)
        return qs

# O sistema sempre irá buscar a primeira classe para depois executar a proxima


class Pagar(DispatchLoginRequeriredMixin, DetailView):
    template_name = 'pedido/pagar.html'
    model = Pedido
    pk_url_kwarg = 'pk'  # parametro vindo da url
    context_object_name = 'pedido'


class SalvarPedido(View):
    template_name = 'pedido/pagar.html'

    def get(self, *args, **kwargs):

        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Faça seu login para continuar!'
            )
            return redirect('perfil:criar')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Seu carrinho está vazio :('
            )
            return redirect('produto:lista')

        carrinho = self.request.session.get('carrinho')
        carrinho_variacao_ids = [id for id in carrinho]
        db_variacoes = list(
            # se puxar mais de 1 tabela, usar o select_related pois faz inner join e transforma e menos consultas
            Variacao.objects.select_related('produto')
            .filter(id__in=carrinho_variacao_ids)
        )

        for variacao in db_variacoes:

            # chave tem que ser string pois esta sendo usada no json
            vid = str(variacao.id)
            estoque = variacao.estoque
            qtd_carrinho = carrinho[vid]['quantidade']
            preco_unt = carrinho[vid]['preco_unitario']
            preco_unt_promo = carrinho[vid]['preco_unitario_promo']

            error_msg_estoque = ''

            if estoque < qtd_carrinho:
                carrinho[vid]['quantidade'] = estoque
                carrinho[vid]['preco_quantitativo'] = estoque * preco_unt
                carrinho[vid]['preco_quantitativo_promo'] = estoque * \
                    preco_unt_promo

                error_msg_estoque = 'Estoque insuficiente para alguns produtos do seu carrinho :( <br>' \
                                    'Reduzimos a quantidade, verique novamente seu carrinho.'

            if error_msg_estoque:
                messages.error(
                    self.request,
                    error_msg_estoque
                )

                self.request.session.save()
                return redirect('produto:carrinho')

        qtd_total_carrinho = helpers.cart_total_items(carrinho)
        valor_total_carrinho = helpers.cart_total_value(carrinho)

        pedido = Pedido(
            usuario=self.request.user,
            total=valor_total_carrinho,
            qtd_total=qtd_total_carrinho,
            status='C',
        )

        pedido.save()

        # bulk_create cria uma queryset com varios objetos, insere no db varios objetos de uma unica vez
        ItemPedido.objects.bulk_create(
            [
                ItemPedido(
                    pedido=pedido,
                    produto=v['produto_nome'],
                    produto_id=v['produto_id'],
                    variacao=v['variacao_nome'],
                    variacao_id=v['variacao_id'],
                    preco=v['preco_quantitativo'],
                    preco_promocional=v['preco_quantitativo_promo'],
                    quantidade=v['quantidade'],
                    imagem=v['imagem'],
                ) for v in carrinho.values()
            ]
        )

        context = {
            'qtd_total_carrinho': qtd_total_carrinho,
            'valor_total_carrinho': valor_total_carrinho
        }

        del self.request.session['carrinho']
        # usado o reserve para passar o id do produto via url
        return redirect(
            reverse(
                'pedido:pagar',
                kwargs={
                    'pk': pedido.pk
                }
            )
        )
        # renderiza = render(self.request, self.template_name, context)


class Detalhe(DispatchLoginRequeriredMixin, DetailView):
    template_name = 'pedido/detalhe.html'
    model = Pedido
    context_object_name = 'pedido'
    pk_url_kwarg = 'pk'


class ListarPedidos(DispatchLoginRequeriredMixin, ListView):
    template_name = 'pedido/listarpedidos.html'
    model = Pedido
    context_object_name = 'pedidos'
    paginate_by = 4
    ordering = ['-id']

pedido/templates/pedido/detalhe.html
{% extends 'base.html' %}
{% load static %}
{% load filters %}

{% block title %}Detalhes do pedido{% endblock %}

{% block body %}

{% include 'parts/pedido.html' %}

{% endblock %}

pedido/templates/pedido/listarpedidos.html
{% extends 'base.html' %}
{% load filters %}
{% block title %}Meus pedidos{% endblock %}


{% block body %}

<main class="container mt-4 mb-4">
    <div class="row">
        <div class="col">
            <h3 class="mb-4">Pedidos de {{ user }}</h3>
            <p>Abaixo todos os seus pedidos realizados na loja.</p>

            <div class="table-responsive">
                <table class="table table-striped">
                    <tr>
                        <th scope="col">Pedido</th>
                        <th scope="col">Total</th>
                        <th scope="col">Qtd. Itens</th>
                        <th scope="col">Status</th>
                        <th scope="col">Mais detalhes</th>
                    </tr>

                    {% for pedido in pedidos %}
                    <tr>
                        <th scope="row">Pedido N. {{ pedido.id }}
                        </td>
                        <td>{{ pedido.total|formata_preco }}</td>
                        <td>{{ pedido.qtd_total }}</td>
                        <td>{{ pedido.get_status_display }}</td>
                        <td>
                            <!-- pedido.id é a primary key passada para a url no arquivo urls -->
                            <a href="{% url 'pedido:detalhe' pedido.id %}">
                                Ver <i class="fas fa-search-plus ml-2"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</main>

{% include 'parts/pagination.html' %}

{% endblock %}

pedido/templates/pedido/pagar.html
{% extends 'base.html' %}
{% load static %}
{% load filters %}
{% block title %}Pagamento{% endblock %}

{% block body %}

<main class="container mt-4 mb-4">
    <div class="row">
        <div class="col">
            <h3>Escolha o método de pagamento</h3>
            <p>Para o desenvolvedor: adicione seu método de pagamento preferido.</p>
        </div>
    </div>

    {% include 'parts/pedido.html' %}
    <div class="row mt-4">
        <div class="col">
            <a href="#" class="btn btn-primary btn-block btn-lg">Pagar</a>
        </div>
    </div>
</main>

{% endblock %}

pedido/templates/pedido/salvarpedido.html
{% extends 'base.html' %}