loja/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TODO: Remover
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('listarpedidos/', views.ListarPedidos.as_view(), name='listarpedidos'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

produto/urls.py
from django.urls import path
from . import views

# app_name é como se fosse um name space, é utilizado nos templates ex de uso:
# utilizando na action do formulario action="produto:urldesejada"
# ex: produto:adicionaraocarrinho
app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name='lista'),
    path('<slug>', views.DetalheProduto.as_view(), name='detalhe'),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(), name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(), name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),
    path('busca/', views.Busca.as_view(), name='busca')
]

produto/models.py
from django.db import models
from PIL import Image
import os
from django.conf import settings
from django.utils.text import slugify
from helpers import helpers
from categorias.models import Category

class Produto(models.Model):

    nome = models.CharField(max_length=150)
    categoria = models.ForeignKey(Category, default=1, on_delete=models.DO_NOTHING)
    descricao_longa = models.TextField(max_length=255)
    descricao_curta = models.TextField()
    imagem = models.ImageField(upload_to='product_images/%Y/%m', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco_marketing = models.FloatField(verbose_name='Preço')
    preco_marketing_promocional = models.FloatField(default=0, verbose_name='Preço Promo')
    tipo = models.CharField(  #cria um select no admin
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variação'),
            ('S', 'Simples'),
        )
    )

    def get_preco_formatado(self):
        return helpers.formata_preco(self.preco_marketing)
    get_preco_formatado.short_description = 'Preço'

    def get_preco_promocional_formatado(self):
        return helpers.formata_preco(self.preco_marketing_promocional)
    get_preco_promocional_formatado.short_description = 'Preço Promo'

    #salva a imagem no admin
    def save(self, *args, **kwargs):

        if not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug

        super().save(*args, **kwargs)

        max_image_size = 800

        #se existir uma imagem, manda a imagem do model e o tamanho pro metodo statico
        if self.imagem:
            helpers.resize_image(self.imagem, max_image_size)

    def __str__(self):
        return self.nome

class Variacao(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50, blank=True, null=True)
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.nome or self.produto.nome

    #no admin mostra o nome da class, esta class altera o nome de exibição
    class Meta:
        verbose_name = 'Variavel'
        verbose_name_plural = 'Variaveis'

produto/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from . import models
from tema.models import Tema
from categorias.models import Category
from perfil.models import Perfil
from django.contrib import messages
from django.db.models import Q  # Q é usado para buscas com filtros
from pprint import pprint  # formata um dicionario para melhor visualização

"""
Reverse pega o http referer anterior do visitante com get()
"""

class ListaProdutos(ListView):
    """
    context_object_name é a variavel que vai para o template
    """
    template_name = 'produto/lista.html'
    context_object_name = 'context'
    queryset = {
        'produto': models.Produto.objects.all(),
        'categoria': Category.objects.all().values_list(),
        'tema': Tema.objects.all().values_list().first(),
    }

class Busca(ListaProdutos):
    def get_queryset(self, *args, **kwargs):
        termo = self.request.GET.get('termo') or self.request.session['termo']
        qs = super().get_queryset(*args, **kwargs)

        if not termo:
            return qs

        self.request.session['termo'] = termo

        qs = qs.filter(
            Q(nome__icontains=termo) |
            Q(descricao_curta__icontains=termo) |
            Q(descricao_longa__icontains=termo)
        )
        self.request.session.save()
        return qs

class DetalheProduto(DetailView):
    """def get(self, *args, **kwargs):
        return HttpResponse('DetalheProduto')"""
    model = models.Produto
    template_name = 'produto/detalhe.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'


class AdicionarAoCarrinho(View):
    def get(self, *args, **kwargs):

        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )
        variacao_id = self.request.GET.get('vid')

        if not variacao_id:
            messages.error(
                self.request,
                'Produto não existe!'
            )
            return redirect(http_referer)

        # tenta pegar o id da variacao do DB se não existir manda um 404
        variacao = get_object_or_404(models.Variacao, id=variacao_id)

        variacao_estoque = variacao.estoque
        produto = variacao.produto  # pega a class variacao e class produto do model

        produto_id = produto.id
        produto_nome = produto.nome
        variacao_nome = variacao.nome or ''
        preco_unitario = variacao.preco
        preco_unitario_promo = variacao.preco_promocional
        quantidade = 1
        slug = produto.slug
        imagem = produto.imagem

        if imagem:
            imagem = imagem.name
        else:
            imagem = ''

        if variacao.estoque < 1:
            messages.warning(
                self.request,
                'Desculpe! Estamos sem estoque deste produto :('
            )
            redirect(http_referer)

        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()

        carrinho = self.request.session['carrinho']

        # verifica se a variacao existe no carrinho
        if variacao_id in carrinho:
            # sempre que vir neste if, o usuário esta tentando adicionar uma nova variacao no carrinho
            quantidade_carrinho = carrinho[variacao_id]['quantidade']
            quantidade_carrinho += 1

            if variacao_estoque < quantidade_carrinho:
                messages.warning(
                    self.request,
                    f'Desculpe! Estamos sem {quantidade_carrinho} unidades de {produto_nome} em estoque! '
                    f'Adicionamos {variacao_estoque} no seu carrinho.'
                )
                quantidade_carrinho = variacao_estoque

            carrinho[variacao_id]['quantidade'] = quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo'] = preco_unitario * quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo_promo'] = preco_unitario_promo * quantidade_carrinho

        else:
            carrinho[variacao_id] = {
                'produto_id': produto_id,
                'produto_nome': produto_nome,
                'variacao_nome': variacao_nome,
                'variacao_id': variacao_id,
                'preco_unitario': preco_unitario,
                'preco_unitario_promo': preco_unitario_promo,
                'preco_quantitativo': preco_unitario,
                'preco_quantitativo_promo': preco_unitario_promo,
                'quantidade': 1,
                'slug': slug,
                'imagem': imagem
            }

        self.request.session.save()
        messages.success(
            self.request,
            'Produto adicionado ao carrinho!'
        )
        return redirect(http_referer)


class RemoverDoCarrinho(View):
    def get(self, *args, **kwargs):

        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )
        variacao_id = self.request.GET.get('vid')

        if not variacao_id:
            return redirect(http_referer)

        if not self.request.session.get('carrinho'):
            return redirect(http_referer)

        if variacao_id not in self.request.session['carrinho']:
            return redirect(http_referer)

        carrinho = self.request.session['carrinho']

        messages.success(
            self.request,
            f'Produto removido do carrinho!'
        )

        del self.request.session['carrinho'][variacao_id]
        self.request.session.save()
        return redirect(http_referer)


class Carrinho(View):
    def get(self, *args, **kwargs):
        context = {
            'carrinho': self.request.session.get('carrinho', {})
        }
        return render(self.request, 'produto/carrinho.html', context)


class ResumoDaCompra(View):
    def get(self, *args, **kwargs):

        perfil = Perfil.objects.filter(usuario=self.request.user).first()

        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')

        if not perfil:
            messages.error(
                self.request,
                'Usuário sem perfil!'
            )
            return redirect('perfil:criar')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Carrinho vazio!'
            )
            return redirect('produto:lista')

        context = {
            'usuario': self.request.user,
            'carrinho': self.request.session['carrinho'],
            'perfil': perfil
        }
        return render(self.request, 'produto/resumodacompra.html', context)

produto/templates/produto/carrinho.html
{% extends 'base.html' %}
{% load filters %}
{% block title %}Carrinho{% endblock %}

{% block body %}
{%  if carrinho %}
<main class="container mt-5 mb-4 pt-4">
    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho de compras</h3>
            <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>
            {% include 'parts/carrinho.html' %}

        </div>
    </div>

    {% else %}

    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho vazio!</h3>
            <p class="lead">Não existem produtos no seu carrinho.</p>
        </div>
    </div>

    {% endif %}

    <div class="row mt-3">
        <div class="col-lg">
            <p class='lead'>Total no carrinho</p>

            <div class='table-responsive'>
                <table class="table">
                    <tr>
                        <td class="font-weight-bold">Total</td>
                        <td>{{ carrinho|cart_total_value|formata_preco }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-lg mt-auto">
            {% if request.user.is_authenticated %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'produto:resumodacompra' %}">
                Comprar
            </a>
            {% else %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'perfil:criar' %}">
                Entrar para finalizar a compra
            </a>
            {% endif %}
        </div>
    </div>
</main>
{% endblock %}

produto/templates/produto/detalhe.html
{% extends 'base.html' %}
{% block title %}Ativamente | {{produto.nome}}{% endblock %}
{% load filters %}

{% block body %}
<main class="container mt-5 mb-4 pt-4">
    <div class="row">
        <div class="col-lg-8">
            <div class="row">
                <div class="col-lg">
                    <div class="row no-gutters">
                        <div class="col-lg-12">
                            {% if produto.imagem %}
                            <img class="img-fluid" src="{{ produto.imagem.url }}">
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-lg">
                    <div class="mt-5 mb-5">
                        <h2 class="text-left">{{ produto.nome }}</h2>
                        <p>{{ produto.descricao_longa }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="mt-4 mt-lg-0">
                <!-- | linebreaks (filtro para quebra de linha) -->
                <p class="lead">
                    {% if produto.preco_marketing_promocional %}
                    <span id="variation-preco-promocional" class="lead product-price">
                                {{ produto.preco_marketing_promocional | formata_preco}}
                            </span>
                    <span id="variation-preco" class="lead product-old-price text-muted">
                                {{ produto.preco_marketing | formata_preco}}
                            </span>
                    {% else %}
                    <span id="variation-preco" class="lead product-price">
                                {{ produto.preco_marketing | formata_preco}}
                            </span>
                    {% endif %}
                </p>

                <form action="{% url 'produto:adicionaraocarrinho' %}" id="form-add-to-cart">
                    <div class="form-group">
                        <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                            {% for variacao in produto.variacao_set.all %}
                            <!-- _set.all seleciona todas variacoes-->
                            {% if variacao.preco_promocional %}
                            <option data-preco="{{ variacao.preco | formata_preco }}"
                                    data-preco-promocional="{{ variacao.preco_promocional | formata_preco}}"
                                    value="{{ variacao.id }}">
                                {% if variacao.nome %}
                                {{variacao.nome}}
                                {% else %}
                                {{variacao}}
                                {% endif %}
                            </option>
                            {% else %}
                            <option data-preco="{{ variacao.preco | formata_preco }}"
                                    value="{{ variacao.id }}">
                                {% if variacao.nome %}
                                {{variacao.nome}}
                                {% else %}
                                {{variacao}}
                                {% endif %}
                            </option>
                            {% endif %}
                            {% endfor %}
                        </select>
                    </div>

                    <div class="text-left">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            Adicionar ao carrinho
                        </button>
                    </div>

                </form>


            </div>
        </div>
    </div>
</main>
{% endblock %}

produto/templates/produto/lista.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% load filters %}

{% block body %}
<div id="home-hero-banner" class="container-fluid overflow-hidden">
    <div class="row">
        <!-- Swiper -->
        <div class="swiper-container" id="home-swiper-hero">
            <div class="swiper-wrapper">
                <div class="swiper-slide"><img class="card-img-top"
                                               src="http://s3.amazonaws.com/img.iluria.com/user_layout_theme/2BDB1/slideshow3.jpg?r=0.873598"
                                               alt=""></div>
                <div class="swiper-slide">Slide 2</div>
                <div class="swiper-slide">Slide 3</div>
            </div>
            <!-- Add Pagination -->
            <div class="swiper-pagination"></div>
            <!-- Add Arrows -->
            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
        </div>
    </div>
    <div class="row bg-dark" id="home-hero-sub-banner">
        <div class="col-lg-12">

        </div>
    </div>
</div>
<main class="container mt-5 mb-4 pt-4">
    <div class="row mb-4">
        <!-- Swiper -->
        <div class="swiper-container w-100 home-swiper" id="home-swiper-one">

            <div class="swiper-wrapper">

                {% for produto in context.produto %}
                {% if produto.categoria_id == context.tema.2 %}
                <div class="swiper-slide">

                    <div class="card text-center border-0">
                        {% if produto.imagem %}
                        <a href="{% url 'produto:detalhe' produto.slug %}">
                            <img class="card-img-top" src="{{ produto.imagem.url }}" alt="{{ produto.nome }}">
                        </a>
                        {% endif %}
                        <div class="card-body">
                            <h6 class="card-title">{{ produto.nome }}</h6>
                            <div class="container product-price-block text-center">
                                {% if produto.preco_marketing_promocional %}
                                <span class="product-old-price text-muted">
                                        <small>de</small> {{ produto.preco_marketing | formata_preco}}
                                        </span>
                                <h4 class="font-weight-bold">
                                    {{ produto.preco_marketing_promocional | formata_preco }}
                                </h4>
                                {% else %}
                                <h4 class="font-weight-bold">
                                    {{ produto.preco_marketing | formata_preco}}
                                </h4>
                                {% endif %}
                            </div>
                        </div>
                        <div class="card-footer bg-transparent border-top-light-custom text-center">
                            <a href="{% url 'produto:detalhe' produto.slug %}"
                               class="btn btn-primary btn-sm m-1 btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Comprar
                            </a>
                        </div>
                    </div>

                </div>
                {% endif %}
                {% endfor %}
            </div>

            <!-- Add Pagination -->
            <div class="swiper-pagination"></div>
        </div>
    </div>

    <div class="row">
        <!-- Swiper -->
        <div class="swiper-container w-100 home-swiper" id="home-swiper-two">

            <div class="swiper-wrapper">
                {% for produto in context.produto %}
                {% if produto.categoria_id == context.tema.3 %}
                <div class="swiper-slide">

                    <div class="card text-center border-0">
                        {% if produto.imagem %}
                        <a href="{% url 'produto:detalhe' produto.slug %}">
                            <img class="card-img-top" src="{{ produto.imagem.url }}" alt="{{ produto.nome }}">
                        </a>
                        {% endif %}
                        <div class="card-body">
                            <h6 class="card-title">{{ produto.nome }}</h6>
                            <div class="container product-price-block text-center">
                                {% if produto.preco_marketing_promocional %}
                                <span class="product-old-price text-muted">
                                        <small>de</small> {{ produto.preco_marketing | formata_preco}}
                                        </span>
                                <h4 class="font-weight-bold">
                                    {{ produto.preco_marketing_promocional | formata_preco }}
                                </h4>
                                {% else %}
                                <h4 class="font-weight-bold">
                                    {{ produto.preco_marketing | formata_preco}}
                                </h4>
                                {% endif %}
                            </div>
                        </div>
                        <div class="card-footer bg-transparent border-top-light-custom text-center">
                            <a href="{% url 'produto:detalhe' produto.slug %}"
                               class="btn btn-primary btn-sm m-1 btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Comprar
                            </a>
                        </div>
                    </div>

                </div>
                {% endif %}
                {% endfor %}
            </div>

            <!-- Add Pagination -->
            <div class="swiper-pagination"></div>
        </div>
    </div>


    <div class="row">
        <!-- Swiper -->
        <div class="swiper-container w-100 home-swiper" id="home-swiper-three">

            <div class="swiper-wrapper">
                {% for produto in context.produto %}
                    {% if produto.categoria_id == context.tema.4 %}
                        <div class="swiper-slide">

                        <div class="card text-center border-0">
                            {% if produto.imagem %}
                            <a href="{% url 'produto:detalhe' produto.slug %}">
                                <img class="card-img-top" src="{{ produto.imagem.url }}" alt="{{ produto.nome }}">
                            </a>
                            {% endif %}
                            <div class="card-body">
                                <h6 class="card-title">{{ produto.nome }}</h6>
                                <div class="container product-price-block text-center">
                                    {% if produto.preco_marketing_promocional %}
                                    <span class="product-old-price text-muted">
                                            <small>de</small> {{ produto.preco_marketing | formata_preco}}
                                            </span>
                                    <h4 class="font-weight-bold">
                                        {{ produto.preco_marketing_promocional | formata_preco }}
                                    </h4>
                                    {% else %}
                                    <h4 class="font-weight-bold">
                                        {{ produto.preco_marketing | formata_preco}}
                                    </h4>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="card-footer bg-transparent border-top-light-custom text-center">
                                <a href="{% url 'produto:detalhe' produto.slug %}"
                                   class="btn btn-primary btn-sm m-1 btn-block">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                    Comprar
                                </a>
                            </div>
                        </div>

                    </div>
                    {% endif %}
                {% endfor %}
            </div>

            <!-- Add Pagination -->
            <div class="swiper-pagination"></div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col">
            {% include 'parts/pagination.html' %}
        </div>
    </div>
</main>
{% endblock %}

produto/templates/produto/resumodacompra.html
{% extends 'base.html' %}
{% load filters %}
{% block title %}Resumo da compra{% endblock %}

{% block body %}
<div class="row mb-5">
    <div class="col-lg">
        <h2>Resumo da sua compra</h2>

        <p class="lead">Dados do usuário</p>
        <p>Caso precise editar, <a href="{% url 'perfil:criar' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{ usuario.first_name }}</dd>
            <dt class="col-lg-2">Sobrenome:</dt>
            <dd class="col-lg-4">{{ usuario.last_name }}</dd>

            <dt class="col-lg-2">Idade:</dt>
            <dd class="col-lg-4">{{ perfil.idade }}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{ perfil.data_nascimento}}</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">{{ perfil.cpf }}</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{ usuario.email }}</dd>
        </dl>

        <p class="lead">Dados de endereço</p>
        <p>Caso precise editar, <a href="{% url 'perfil:criar' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Endereço:</dt>
            <dd class="col-lg-4">{{ perfil.endereco }}</dd>
            <dt class="col-lg-2">Número:</dt>
            <dd class="col-lg-4">{{ perfil.numero }}</dd>

            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">{{ perfil.complemento }}</dd>
            <dt class="col-lg-2">Bairro:</dt>
            <dd class="col-lg-4">{{ perfil.bairro }}</dd>

            <dt class="col-lg-2">Cidade:</dt>
            <dd class="col-lg-4">{{ perfil.cidade }}</dd>
            <dt class="col-lg-2">Estado:</dt>
            <dd class="col-lg-4">{{ perfil.estado }}</dd>

            <dt class="col-lg-2">CEP:</dt>
            <dd class="col-lg-4">{{ perfil.cep }}</dd>
        </dl>
    </div>
</div>

<div class="row mt-3">
    <div class="col">
        <h3>Seus produtos</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>
        {% include 'parts/carrinho.html' %}
        <p class="lead text-right font-weight-bold">Total: {{ carrinho|cart_total_value|formata_preco }}</p>
    </div>
</div>

<div class="row">
    <div class="col">
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'pedido:salvarpedido' %}">
            Realizar pedido
        </a>
    </div>
</div>
{% endblock %}